In [13]:
import pandas as pd
import os

In [4]:
df_descriptions = pd.read_csv('files/accommodation_descriptions/descriptions_5900.csv')
df_descriptions

,hotel_name,neighborhood,url,description
0,Relais & Châteaux Hotel Orfila,"Chamberí, Madrid",https://www.booking.com/hotel/es/relais-chatea...,El Hotel Orfila está ubicado en el madrileño b...
1,B&B HOTEL Madrid Carabanchel,"Carabanchel, Madrid",https://www.booking.com/hotel/es/b-amp-b-madri...,B&B HOTEL Madrid Carabanchel es un alojamiento...
2,Market Martinez de la Riva I,"Puente de Vallecas, Madrid",https://www.booking.com/hotel/es/apartamentos-...,Market Martinez de la Riva I está en Madrid y ...
3,Apartamentos Adelfas,"Retiro, Madrid",https://www.booking.com/hotel/es/apartamentos-...,Estos apartamentos modernos y elegantes tienen...
4,Apartamentos Villablino Arturo Soria,"Ciudad Lineal, Madrid",https://www.booking.com/hotel/es/apartamentos-...,Apartamentos Villablino Arturo Soria ofrece al...
...,...,...,...,...
8232,NaN,NaN,NaN,Error: 5893
8233,NaN,NaN,NaN,Error: 5894
8234,NaN,NaN,NaN,Error: 5895
8235,NaN,NaN,NaN,Error: 5896
8236,NaN,NaN,NaN,Error: 5899

It seems that there have been some errors: there are some hotels with missing values, and also the error writing has created new columns instead of filling the columns of the already existing data frame.

In [6]:
df_descriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8237 entries, 0 to 8236
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   hotel_name    5979 non-null   object
 1   neighborhood  5979 non-null   object
 2   url           5979 non-null   object
 3   description   5900 non-null   object
dtypes: object(4)
memory usage: 257.5+ KB

In [8]:
df = pd.DataFrame([[0, 2, 3], [0, 4, 1], [10, 20, 30]], columns=['A', 'B', 'C'])
df

    A   B   C
0   0   2   3
1   0   4   1
2  10  20  30

In [12]:
print(df.at[2, 'B'])

20

In [18]:
url_data_path = "files/accommodation_urls"

# Step 1: import all URL .csv into dataframes in a loop
dataframes = []
# os.listdir(folder_path) lists all files in the specified folder
for file in os.listdir(url_data_path):
    if file.endswith(".csv"):
        file_path = os.path.join(url_data_path, file)
        df_url = pd.read_csv(file_path)
        dataframes.append(df_url)

# Step 2: concatenate all dataframes along the rows (indexes, axis = 0)
df_url_combined = pd.concat(dataframes, axis=0, ignore_index=True)

# Step 3: keep only unique values among a subset of columns (so that the extraction
# of descriptions is more efficient)
df_url_unique = df_url_combined.drop_duplicates(subset=['hotel_name']).reset_index(drop = True)

In [19]:
df_url_unique

,hotel_name,neighborhood,url
0,Relais & Châteaux Hotel Orfila,"Chamberí, Madrid",https://www.booking.com/hotel/es/relais-chatea...
1,B&B HOTEL Madrid Carabanchel,"Carabanchel, Madrid",https://www.booking.com/hotel/es/b-amp-b-madri...
2,Market Martinez de la Riva I,"Puente de Vallecas, Madrid",https://www.booking.com/hotel/es/apartamentos-...
3,Apartamentos Adelfas,"Retiro, Madrid",https://www.booking.com/hotel/es/apartamentos-...
4,Apartamentos Villablino Arturo Soria,"Ciudad Lineal, Madrid",https://www.booking.com/hotel/es/apartamentos-...
...,...,...,...
5974,For You Rentals Acogedor Apartamento TEMPORAL ...,"Centro de Madrid, Madrid",https://www.booking.com/hotel/es/for-you-renta...
5975,For You Rentals Encantador apartamento TEMPORA...,"Centro de Madrid, Madrid",https://www.booking.com/hotel/es/for-you-renta...
5976,Elegant Apartment in the Heart of Madrid 100m²...,"Centro de Madrid, Madrid",https://www.booking.com/hotel/es/apartment-cal...
5977,For You Rentals Hermoso apartamento TEMPORAL P...,"Centro de Madrid, Madrid",https://www.booking.com/hotel/es/habitaciones-...
5978,Metropolitano en Madrid,"San Blas, Madrid",https://www.booking.com/hotel/es/mit-house-met...